### ISSUE TITLE
How to get all Front-matters available at the begining of every post

### ISSUE THREAD

**Issue by HelloLyfing** [mmistakes/hpstr-jekyll-theme#11]
[Front-matters](http://jekyllrb.com/docs/frontmatter/), which is the stuff thing at the begining of every post, like things below:

```

---
layout: post
title: Blogging Like a Hacker
anything more ?

---
```

As far as I know, it includes: 

```

---
layout: post
title: Sample Post
description: "Just about everything you'll need to style in the theme: headings, paragraphs, blockquotes, tables, code blocks, and more."
modified: 2013-05-31
tags: [sample post]
image:
  feature: abstract-3.jpg
  credit: dargadgetz
  creditlink: http://www.dargadgetz.com/ios-7-abstract-wallpaper-pack-for-iphone-5-and-ipod-touch-retina/
comments: true
share: true

---
```

Do we have anything more ?
