### ISSUE TITLE
A blank area and the bottom scroll bar will appear when in iPhone.

### ISSUE THREAD

**Issue by shukai0828** [mmistakes/hpstr-jekyll-theme#63]
It can be resolved by add a line to _sass/_page.scss. As below.

``` css
#post-index {
    #main {
        margin: 40px 2px 20px 2px;
        // add this line: overflow: hidden
        overflow: hidden;
        @media #{$medium} {
            margin-left: 20px;
            margin-right: 20px;
        }
        @media #{$large} {
            max-width: 800px;
            margin-top: 50px;
            margin-left: auto;
            margin-right: auto;
        }
    }
```
