### ISSUE TITLE
Tag CSS Color on Posts

### ISSUE THREAD

**Issue by justinrummel** [mmistakes/hpstr-jekyll-theme#77]
I'm not a CSS expert, but was confused when I found in the _page.scss for the .tag section, there are two lines for "color:"

https://github.com/mmistakes/hpstr-jekyll-theme/blob/master/_sass/_page.scss#L175-177

Also, the default color is $white which does not display with a white background. If you replace one of the $white with $text-color it does display, however, I want to make sure these are the right lines of CSS to modify, thus: 

``` bash
//		color: $white;
		@include rounded(3px);
		color: $text-color;
```

**Comment by mmistakes** [comment]
There should only be one `color: $white;` declaration. You can safely remove one.

![tag-pills](https://cloud.githubusercontent.com/assets/1376749/5729423/48955628-9b40-11e4-9ed0-4d240b25e801.png)

The current style is white text on a gray background for the tag "pills". Here are the important parts you'll want to modify to change the colors.

``` css
.tag {
	color: $white; // tag text color
	.term {
		background-color: lighten($base-color,60); // background color of tag name text
	}
	.count {
		background-color: lighten($base-color,40); // background color of tag count to the right of the term name
	}
	&:hover {
		background-color: lighten($base-color,50); // background color when tag link is hovered
	}
}
```
